apiVersion: v1
kind: Pod
metadata:
  name: no-restart-memhog-pod
spec:
  restartPolicy: Never
  containers:
  - name: memhog
    image: memhog:v0.1.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "256Mi"
      limits:
        memory: "256Mi"
